### ISSUE TITLE
"Index of /downloads" indexed by Google

### ISSUE THREAD

**Issue by phidrho** [qgis/QGIS-Website#665]
### URL

https://google.com

### Type(s) of Problems

Other

### Summary

Hi,

I just searched for "qgis" on google and got one weird result - a link to "Index of... downloads folder":

![Image](https://github.com/user-attachments/assets/4b471f7b-1eb5-4051-a76b-b68e30d367f1)

Link is leading to this website: https://download.qgis.org/downloads/

Since one link above that one (see image) is leading to proper Download site - https://qgis.org/download/

I think that this one should be discuraged/forbidden for web scrapers.

One possible solution is to add robots.txt to "Index of..." website folder or there is smarter way by setting Apache webserver options for Apache Directory Listing.

**Comment by phidrho** [comment]
@timlinux sorry for `good first issue` label, please remove it

**Comment by Xpirix** [comment]
Thanks for this @phidrho . I have disallowed it in #711. However, I don't see it in the result anymore. Perhaps, it has been fixed from the download folder.

<img width="1018" height="746" alt="Image" src="https://github.com/user-attachments/assets/bbea81cb-1743-4689-a5d9-1a0a7d2e8f99" />

**Comment by phidrho** [comment]
I still get it but a little bit lower on list.

![Screenshot_2025-09-12-14-21-17-489_com.android.chrome.jpg](https://github.com/user-attachments/assets/646d4ba1-d5f8-490d-af58-5091d5adc034)

**Comment by Xpirix** [comment]
@phidrho , I have merged the PR. I will check later if it has any effect. Otherwise, I will try another approach.

**Comment by phidrho** [comment]
@Xpirix
I think that google needs some time to process everything. So maybe we can check in a week...

**Comment by phidrho** [comment]
It's still present in croatian version of google, but it's lowered down in results - that is a progress:

<img width="727" height="603" alt="Image" src="https://github.com/user-attachments/assets/da34e83f-76a3-43ef-8d93-9eb7a4cf97bd" />

**Comment by Xpirix** [comment]
Okay, I will investigate more on it later. Thanks @phidrho .

**Comment by phidrho** [comment]
Hi @Xpirix,

I just tested it again, it seems good :)

<img width="843" height="677" alt="Image" src="https://github.com/user-attachments/assets/59f980b9-653b-4280-ba19-cb36aad47dc3" />

**Comment by Xpirix** [comment]
Great! Thanks @phidrho .
